server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://47.98.140.228:3306/shield
    username: root
    password: root
  application:
    name: security-demo
  session:
    store-type: none
shield:
  security:
    browser:
#      loginPage: /newLogin.html
      loginType: JSON
    validateCode:
      imageCodeProperties:
        width: 200
        height: 100
        length: 6
        urls:
          - /user/*
      smsCodeProperties:
        length: 7
    social:
      qq:
        app-id: 101386962
#        providerId: 2a0f820407df400b84a854d054be8b6a
        providerId: qq
        app-secret: qq
        filterProcessesUrl: /login


