server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://47.98.140.228:3306/crs
    username: root
    password: root
  application:
    name: security-demo
  session:
    store-type: none
shield:
  security:
    browser:
#      loginPage: /newLogin.html
      loginType: JSON
    validateCode:
      imageCodeProperties:
        width: 200
        height: 100
        length: 6
        urls:
          - /user/*
      smsCodeProperties:
        length: 7


