server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://47.98.140.228:3306/crs
    username: root
    password: root
  application:
    name: security-demo
  session:
    store-type: none
security:
  basic:
    enabled: false